
name: Browser Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install project dependencies
        run: npm ci --legacy-peer-deps

      - name: Detect Chrome major version
        id: chrome
        run: |
          CHROME_VER=$(google-chrome --version | sed -E 's/.* ([0-9]+)\..*/\1/')
          echo "Detected Chrome v$CHROME_VER"
          echo "major=$CHROME_VER" >> $GITHUB_OUTPUT

      - name: Override Chromedriver to match Chrome
        run: npm install --no-save chromedriver@${{ steps.chrome.outputs.major }}

      - name: Verify Chromedriver
        run: npx chromedriver --version

      - name: Build (if needed)
        run: npm run build --if-present

      - name: Run Nightwatch
        run: npm run test:e2e


